name: SWERI Processing dev
services:
  app:
    volumes:
      - ..:/src
      - ~/.aws:/root/.aws:ro
  celery:
    volumes:
      - ..:/src
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - "../.env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"  
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${HOST_PGADMIN_DATA_PATH}:/var/lib/pgadmin


volumes:
  postgres_data:
